package:
  name: smarty
  version: 0.1.4

source:
  git_url: https://github.com/open-forcefield-group/smarty.git
  git_tag: 0.1.4

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - networkx
    - lxml

test:
  requires:
    - nose
    - nose-timer
#  imports:
#    - smarty
#  commands:
#    - smarty

about:
  home: https://github.com/open-forcefield-group/smarty
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
