package:
  name: openbabel
  # The version epoch format of E!X.Y.Z must be applied since OpenBabel started with YEAR.MO format.
  # Version epoch allows newer X.Y.Z format to take priority as later packages than the YEAR.MO format
  # See PEP 440 and conda-build VersionOrder class
  version: "1!2.4.0"

source:
  url: https://github.com/openbabel/openbabel/archive/openbabel-2-4-0.zip 
  fn: openbabel-2-4-0.zip 

  patches:
    - include-dirs.patch
    - fix_library_path_search.diff
    - fix_data_path.diff

build:
  number: 2
  detect_binary_files_with_prefix: true
  skip: True  # [win]

requirements:
  build:
    - cmake
    - zlib
    - swig
    - bzip2
    - python
    - zlib
    - libxml2
  run:
    - python
    - zlib
    - libxml2

about:
    home: http://www.openbabel.org/
    license: GPLv2
    summary: "A chemical toolbox designed to speak the many languages of chemical data"
