package:
  name: progress_reporter
  version: "1.3.1"

source:
  git_url: https://github.com/marscher/progress_reporter
  git_rev: v1.3.1

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - progress_reporter
    - progress_reporter.bar

about:
  home: https://github.com/marscher/progress_reporter
  license: MIT License
  summary: 'interface for progress reporting'

extra:
  maintainers: Martin Scherer
